# WORK frontend
FROM node:15-alpine as frontend

# Copy source
COPY . /app

# Installing dependencies
RUN cd /app && yarn && yarn run build

# WORK app
FROM node:15-alpine

# For start
COPY --from=frontend /app/.next /app/.next
COPY --from=frontend /app/public /app/public
COPY --from=frontend /app/node_modules /node_modules
COPY --from=frontend /app/package.json /

# Running the app
CMD yarn run start /app