version: '3.7'

services:
    nestjs:
        build:
            context: ./backend
        ports:
            - 4000:4000
        volumes:
            - .:/app/backend
            - /app/backend/node_modules
        env_file:
            - backend/.env.template
            - backend/.env.local # need to add

    nextjs:
        depends_on:
            - nestjs
        build:
            context: ./frontend
        ports:
            - 3000:3000
        volumes:
            - .:/app/frontend
            - /app/frontend/node_modules
        env_file:
            - frontend/.env.template
            - frontend/.env.local # can be removed

